/****** Object:  Table [inventory].[SQLEdition]    Script Date: 03-04-2026 15:48:46 ******/
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [inventory].[SQLEdition](
	[SQLEditionID] [int] IDENTITY(1,1) NOT NULL,
	[SQLEditionName] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
 CONSTRAINT [PK_SQLEdition] PRIMARY KEY CLUSTERED 
(
	[SQLEditionID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

SET ANSI_PADDING ON

/****** Object:  Index [UX_SQLEdition_Name]    Script Date: 03-04-2026 15:48:46 ******/
CREATE UNIQUE NONCLUSTERED INDEX [UX_SQLEdition_Name] ON [inventory].[SQLEdition]
(
	[SQLEditionName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
