/****** Object:  Table [inventory].[SQLVersion]    Script Date: 03-04-2026 15:48:48 ******/
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [inventory].[SQLVersion](
	[SQLVersionID] [int] IDENTITY(1,1) NOT NULL,
	[SQLVersionName] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
 CONSTRAINT [PK_SQLVersion] PRIMARY KEY CLUSTERED 
(
	[SQLVersionID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

SET ANSI_PADDING ON

/****** Object:  Index [UX_SQLVersion_Name]    Script Date: 03-04-2026 15:48:48 ******/
CREATE UNIQUE NONCLUSTERED INDEX [UX_SQLVersion_Name] ON [inventory].[SQLVersion]
(
	[SQLVersionName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
