/****** Object:  Table [inventory].[ServerIP]    Script Date: 03-04-2026 15:48:46 ******/
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [inventory].[ServerIP](
	[IPID] [int] IDENTITY(1,1) NOT NULL,
	[ServerID] [int] NOT NULL,
	[IPAddress] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[IPAddressTypeID] [int] NOT NULL,
	[IsActive] [bit] NOT NULL,
 CONSTRAINT [PK_ServerIP] PRIMARY KEY CLUSTERED 
(
	[IPID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

/****** Object:  Index [IX_ServerIP_ServerID]    Script Date: 03-04-2026 15:48:46 ******/
CREATE NONCLUSTERED INDEX [IX_ServerIP_ServerID] ON [inventory].[ServerIP]
(
	[ServerID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
SET ANSI_PADDING ON

/****** Object:  Index [UX_ServerIP_Address]    Script Date: 03-04-2026 15:48:46 ******/
CREATE UNIQUE NONCLUSTERED INDEX [UX_ServerIP_Address] ON [inventory].[ServerIP]
(
	[IPAddress] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
ALTER TABLE [inventory].[ServerIP] ADD  DEFAULT ((1)) FOR [IsActive]
ALTER TABLE [inventory].[ServerIP]  WITH CHECK ADD  CONSTRAINT [FK_ServerIP_Server] FOREIGN KEY([ServerID])
REFERENCES [inventory].[Server] ([ServerID])
ALTER TABLE [inventory].[ServerIP] CHECK CONSTRAINT [FK_ServerIP_Server]
ALTER TABLE [inventory].[ServerIP]  WITH CHECK ADD  CONSTRAINT [FK_ServerIP_Type] FOREIGN KEY([IPAddressTypeID])
REFERENCES [inventory].[IPAddressType] ([IPAddressTypeID])
ALTER TABLE [inventory].[ServerIP] CHECK CONSTRAINT [FK_ServerIP_Type]
