/****** Object:  Table [inventory].[OSType]    Script Date: 03-04-2026 15:48:45 ******/
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [inventory].[OSType](
	[OSID] [int] IDENTITY(1,1) NOT NULL,
	[OperatingSystem] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[OSCategory] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 CONSTRAINT [PK_OSType] PRIMARY KEY CLUSTERED 
(
	[OSID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

SET ANSI_PADDING ON

/****** Object:  Index [UX_OSType_Name]    Script Date: 03-04-2026 15:48:45 ******/
CREATE UNIQUE NONCLUSTERED INDEX [UX_OSType_Name] ON [inventory].[OSType]
(
	[OperatingSystem] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
