USE [master]
GO

CREATE DATABASE [SQLInventory]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SQLInventory', FILENAME = N'E:\Data\SQLInventory.mdf' , SIZE = 73728KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SQLInventory_log', FILENAME = N'G:\Log\SQLInventory_log.ldf' , SIZE = 73728KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SQLInventory].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SQLInventory] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SQLInventory] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SQLInventory] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SQLInventory] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SQLInventory] SET ARITHABORT OFF 
GO

ALTER DATABASE [SQLInventory] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [SQLInventory] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SQLInventory] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SQLInventory] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SQLInventory] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SQLInventory] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SQLInventory] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SQLInventory] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SQLInventory] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SQLInventory] SET  ENABLE_BROKER 
GO

ALTER DATABASE [SQLInventory] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SQLInventory] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SQLInventory] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SQLInventory] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SQLInventory] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SQLInventory] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SQLInventory] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SQLInventory] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [SQLInventory] SET  MULTI_USER 
GO

ALTER DATABASE [SQLInventory] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SQLInventory] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SQLInventory] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SQLInventory] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [SQLInventory] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [SQLInventory] SET QUERY_STORE = ON
GO

ALTER DATABASE [SQLInventory] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200)
GO

USE [SQLInventory]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [SQLInventory] SET  READ_WRITE 
GO

